site_name: Тестовая документация
site_description: Документация и руководство пользователя
site_url: https://Glebded.github.io/itcafe24Doc/

theme:
  name: readthedocs
  # name: material
  # palette:
  #   scheme: slate # Тёмная тема по умолчанию (как в Blender)
  #   primary: indigo
  # features:
  #   - navigation.tabs
  #   - search.suggest
markdown_extensions:
- admonition
# - pymdownx.details  # Добавляет поддержку раскрывающихся блоков (??? question)
# - pymdownx.superfences

nav:
  - Overview: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - Настройка нового проекта: setup_new_doc_project.md
